DELETE TABLE IF EXISTS user_chats;
DELETE TABLE IF EXISTS chatmessages
DELETE TABLE IF EXISTS posts;
DELETE TABLE IF EXISTS post_custom_privacy;
DELETE TABLE IF EXISTS notifications;
DELETE TABLE IF EXISTS comments;
DELETE TABLE IF EXISTS group_events;
DELETE TABLE IF EXISTS group_event_interest;